#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre on Sun Aug 23 22:39:30 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ContactAnnotationGUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ContactAnnotationGUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((336, 243))
        self.SetTitle("Kontaktdetails")
        
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        
        grid_sizer_1 = wx.FlexGridSizer(8, 3, 5, 5)
        
        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_2, 0, 0, 0)
        
        static_text_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Position")
        grid_sizer_1.Add(static_text_14, 0, 0, 0)
        
        static_text_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Steckerbezeichnung")
        grid_sizer_1.Add(static_text_15, 0, 0, 0)
        
        static_text_8 = wx.StaticText(self.panel_1, wx.ID_ANY, u"0.24 mm²")
        grid_sizer_1.Add(static_text_8, 0, 0, 0)
        
        self.text_ctrl_12 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_12.SetMinSize((100, 22))
        grid_sizer_1.Add(self.text_ctrl_12, 0, 0, 0)
        
        self.text_ctrl_18 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_18.SetMinSize((150, 22))
        grid_sizer_1.Add(self.text_ctrl_18, 0, 0, 0)
        
        static_text_9 = wx.StaticText(self.panel_1, wx.ID_ANY, u"0.34 mm²")
        grid_sizer_1.Add(static_text_9, 0, 0, 0)
        
        self.text_ctrl_13 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_13, 0, 0, 0)
        
        self.text_ctrl_19 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_19.SetMinSize((150, 22))
        grid_sizer_1.Add(self.text_ctrl_19, 0, 0, 0)
        
        static_text_10 = wx.StaticText(self.panel_1, wx.ID_ANY, u"0.75 mm²")
        grid_sizer_1.Add(static_text_10, 0, 0, 0)
        
        self.text_ctrl_14 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_14, 0, 0, 0)
        
        self.text_ctrl_20 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_20.SetMinSize((150, 22))
        grid_sizer_1.Add(self.text_ctrl_20, 0, 0, 0)
        
        static_text_11 = wx.StaticText(self.panel_1, wx.ID_ANY, u"1.00 mm²")
        grid_sizer_1.Add(static_text_11, 0, 0, 0)
        
        self.text_ctrl_15 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_15, 0, 0, 0)
        
        self.text_ctrl_21 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_21.SetMinSize((150, 22))
        grid_sizer_1.Add(self.text_ctrl_21, 0, 0, 0)
        
        static_text_12 = wx.StaticText(self.panel_1, wx.ID_ANY, u"1.50 mm²")
        grid_sizer_1.Add(static_text_12, 0, 0, 0)
        
        self.text_ctrl_16 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_16, 0, 0, 0)
        
        self.text_ctrl_22 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_22.SetMinSize((150, 22))
        grid_sizer_1.Add(self.text_ctrl_22, 0, 0, 0)
        
        static_text_13 = wx.StaticText(self.panel_1, wx.ID_ANY, u"2.50 mm²")
        grid_sizer_1.Add(static_text_13, 0, 0, 0)
        
        self.text_ctrl_17 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_17, 0, 0, 0)
        
        self.text_ctrl_23 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_23.SetMinSize((150, 22))
        grid_sizer_1.Add(self.text_ctrl_23, 0, 0, 0)
        
        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)
        
        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_1.Add(self.panel_4, 1, wx.EXPAND, 0)
        
        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, u"Übernehmen")
        grid_sizer_1.Add(self.button_1, 0, wx.ALIGN_RIGHT, 0)
        
        self.panel_1.SetSizer(grid_sizer_1)
        
        self.Layout()
        # end wxGlade

# end of class ContactAnnotationGUI

class MyApp(wx.App):
    def OnInit(self):
        self.frame = ContactAnnotationGUI(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
