#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre on Fri Sep 18 11:11:29 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class OrderDetailsGUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: OrderDetailsGUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((340, 164))
        self.SetTitle("OrderDetailsGUI")
        
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 5, 5)
        sizer_1.Add(grid_sizer_1, 0, wx.ALL, 5)
        
        st1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Bestellnummer:")
        st1.SetMinSize((99, 16))
        grid_sizer_1.Add(st1, 0, 0, 0)
        
        self.tcOrderNr = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tcOrderNr.SetMinSize((200, 22))
        grid_sizer_1.Add(self.tcOrderNr, 0, 0, 0)
        
        st2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Auftragsnummer:")
        grid_sizer_1.Add(st2, 0, 0, 0)
        
        self.tcJobNr = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tcJobNr.SetMinSize((200, 22))
        grid_sizer_1.Add(self.tcJobNr, 0, 0, 0)
        
        st3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Belegnummer:")
        grid_sizer_1.Add(st3, 0, 0, 0)
        
        self.tcReceiptNr = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tcReceiptNr.SetMinSize((200, 22))
        grid_sizer_1.Add(self.tcReceiptNr, 0, 0, 0)
        
        static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        sizer_1.Add(static_line_1, 0, wx.ALL | wx.EXPAND, 5)
        
        self.btnPrint = wx.Button(self.panel_1, wx.ID_ANY, "Drucken")
        self.btnPrint.Enable(False)
        sizer_1.Add(self.btnPrint, 0, wx.ALIGN_RIGHT | wx.ALL, 5)
        
        self.panel_1.SetSizer(sizer_1)
        
        self.Layout()
        # end wxGlade

# end of class OrderDetailsGUI

class MyApp(wx.App):
    def OnInit(self):
        self.frame = OrderDetailsGUI(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
