#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre on Wed Sep 23 07:00:59 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SettingsDialogGUI(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SettingsDialogGUI.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE | wx.STAY_ON_TOP
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((781, 509))
        self.SetTitle("Allgemeine Einstellungen")
        self.SetFocus()
        
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        
        self.lcXSections = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.lcXSections.SetMinSize((377, -1))
        self.lcXSections.AppendColumn("Querschnitt", format=wx.LIST_FORMAT_LEFT, width=100)
        self.lcXSections.AppendColumn("offener Kontakt (N)", format=wx.LIST_FORMAT_LEFT, width=110)
        self.lcXSections.AppendColumn("geschlosseneer Kontakt (N)", format=wx.LIST_FORMAT_LEFT, width=155)
        sizer_2.Add(self.lcXSections, 1, wx.EXPAND | wx.LEFT | wx.TOP, 5)
        
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        
        grid_sizer_1 = wx.FlexGridSizer(2, 3, 5, 5)
        sizer_3.Add(grid_sizer_1, 0, 0, 0)
        
        static_text_3 = wx.StaticText(self, wx.ID_ANY, "Querschnitt:")
        grid_sizer_1.Add(static_text_3, 0, wx.LEFT | wx.TOP, 5)
        
        static_text_4 = wx.StaticText(self, wx.ID_ANY, "offener Kontakt (N)")
        grid_sizer_1.Add(static_text_4, 0, wx.TOP, 5)
        
        static_text_5 = wx.StaticText(self, wx.ID_ANY, "geschlossener Kontakt (N)")
        grid_sizer_1.Add(static_text_5, 0, wx.RIGHT | wx.TOP, 5)
        
        self.tcXSection = wx.TextCtrl(self, wx.ID_ANY, "")
        grid_sizer_1.Add(self.tcXSection, 0, wx.LEFT, 5)
        
        self.tcSollOpen = wx.TextCtrl(self, wx.ID_ANY, "")
        self.tcSollOpen.SetMinSize((121, 22))
        grid_sizer_1.Add(self.tcSollOpen, 0, 0, 0)
        
        self.tcSollClosed = wx.TextCtrl(self, wx.ID_ANY, "")
        self.tcSollClosed.SetMinSize((165, 22))
        grid_sizer_1.Add(self.tcSollClosed, 0, wx.RIGHT, 5)
        
        self.btnSave = wx.Button(self, wx.ID_ANY, "Speichern")
        self.btnSave.SetMinSize((100, 21))
        self.btnSave.Enable(False)
        sizer_3.Add(self.btnSave, 0, wx.ALL, 5)
        
        self.btnDelete = wx.Button(self, wx.ID_ANY, "Entfernen")
        self.btnDelete.SetMinSize((100, 21))
        self.btnDelete.Enable(False)
        sizer_3.Add(self.btnDelete, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 5)
        
        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        sizer_3.Add(self.panel_2, 1, wx.EXPAND, 0)
        
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_4, 0, wx.EXPAND, 0)
        
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        sizer_4.Add(self.panel_1, 1, wx.EXPAND, 0)
        
        self.btnApply = wx.Button(self, wx.ID_ANY, u"Übernehmen")
        self.btnApply.Enable(False)
        sizer_4.Add(self.btnApply, 0, wx.BOTTOM | wx.RIGHT, 5)
        
        self.SetSizer(sizer_1)
        
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class SettingsDialogGUI

class MyApp(wx.App):
    def OnInit(self):
        self.frame = SettingsDialogGUI(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
